name: Docker Image CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build the Builder image
      run: |
        export BRANCH_NAME=`echo $GITHUB_REF | sed "s/refs\/heads\///"`
        export CACHE_IMAGE=diverofdark/antifilter:`echo $BRANCH_NAME | tr '/' '_'  | tr '@' '_'`
        docker build -t $CACHE_IMAGE . -f Dockerfile.builder

    - name: Push the BudgetTracker image
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      env: 
        DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        export BRANCH_NAME=`echo $GITHUB_REF | sed "s/refs\/heads\///"`
        export CACHE_IMAGE=diverofdark/antifilter:`echo $BRANCH_NAME | tr '/' '_'  | tr '@' '_'`

        docker login --username="$DOCKER_LOGIN" --password="$DOCKER_PASSWORD"
        docker push $CACHE_IMAGE
